DROP TABLE IF EXISTS bridge_maps CASCADE;
CREATE TABLE bridge_maps (
  id SERIAL PRIMARY KEY NOT NULL,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  odd_id INTEGER REFERENCES odd_jobs(id) ON DELETE CASCADE
);
